### GET /
GET http://localhost:8080 HTTP/1.1

### GET /users
GET http://localhost:8080/users HTTP/1.1

### POST /auth/register
POST http://localhost:8080/auth/register HTTP/1.1
Content-Type: application/json

{
  	"email": "john@gmail.com",
  	"password": "John123!",
  	"confirmPassword": "John123!"
}

### POST /auth/login
POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
  	"email": "john@gmail.com",
  	"password": "John123!"
}

### GET /auth
GET http://localhost:8080/auth HTTP/1.1

### POST /auth/signout
POST http://localhost:8080/auth/signout HTTP/1.1

### GET /permissions
GET http://localhost:8080/permissions HTTP/1.1

### POST /permissions
POST http://localhost:8080/permissions HTTP/1.1
Content-Type: application/json

{
	"name": "edit_orders"
}

### GET /roles
GET http://localhost:8080/roles

### POST /roles
POST http://localhost:8080/roles HTTP/1.1
Content-Type: application/json

{
	"name": "Viewer",
	"permissions": []
}

### PATCH /roles/:id
PATCH http://localhost:8080/roles/:id HTTP/1.1
Content-Type: application/json

{
	"name": "Admin",
	"permissions": []
}

### DELETE /roles/:id
DELETE  http://localhost:8080/roles/ec9d1d72-338d-4760-a36c-694d7166555c HTTP/1.1

### PATCH /users/:id
PATCH http://localhost:8080/users/737cd16e-352f-4fec-9f47-daf74857e003 HTTP/1.1
Content-Type: application/json

{
	"role_id": "51149c12-be54-4fe2-9b3e-df84b640d76b"
}